import { Event } from '../types/event';

export const mockEvents: Event[] = [
    {
        id: '1',
        name: 'Summer Music Festival',
        displayPicture: 'https://images.unsplash.com/photo-1582192493926-93f4847e1323?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        dateTime: '2023-07-15T18:00:00',
        description: 'A vibrant celebration of music under the summer sky.',
        maxParticipants: 5000,
        ticketPrice: '0.05 ETH',
        location: 'Central Park, New York',
        mainGuests: ['DJ Sparkle', 'The Rockers', 'Synth Sisters'],
    },
    {
        id: '2',
        name: 'Tech Innovation Conference',
        displayPicture: 'https://images.unsplash.com/photo-1504384764586-bb4cdc1707b0?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        dateTime: '2023-09-22T09:00:00',
        description: 'Exploring the future of technology and its impact on society.',
        maxParticipants: 1000,
        ticketPrice: '0.1 ETH',
        location: 'Silicon Valley Convention Center',
        mainGuests: ['Elon Musk', 'Satya Nadella', 'Lisa Su'],
    },
    {
        id: '3',
        name: 'Art & Wine Evening',
        displayPicture: 'https://www.lokiwine.co.uk/wp-content/uploads/2024/07/Wine-and-art.jpeg',
        dateTime: '2023-08-20T19:00:00',
        description: 'An elegant evening of fine art and exquisite wines.',
        maxParticipants: 300,
        ticketPrice: '0.02 ETH',
        location: 'Art Museum, San Francisco',
        mainGuests: ['Claude Monet', 'Vincent van Gogh', 'Georgia O\'Keeffe'],
    },
    {
        id: '4',
        name: 'Blockchain Summit 2023',
        displayPicture: 'https://dcblockchainsummit.com/wp-content/uploads/2023/03/202303121JB-0542-scaled.jpg',
        dateTime: '2023-11-10T10:00:00',
        description: 'A deep dive into blockchain technology and its future applications.',
        maxParticipants: 2000,
        ticketPrice: '0.08 ETH',
        location: 'Convention Center, Dubai',
        mainGuests: ['Vitalik Buterin', 'Charlie Lee', 'Gavin Wood'],
    },
    {
        id: '5',
        name: 'Culinary World Tour',
        displayPicture: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=2670&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D',
        dateTime: '2023-12-05T17:00:00',
        description: 'Taste the world\'s finest cuisines in one place.',
        maxParticipants: 800,
        ticketPrice: '0.03 ETH',
        location: 'Gourmet Plaza, Paris',
        mainGuests: ['Gordon Ramsay', 'Massimo Bottura', 'Alice Waters'],
    },
    {
        id: '6',
        name: 'Outdoor Adventure Expo',
        displayPicture: 'https://i.ytimg.com/vi/9JaLzqhHlYY/maxresdefault.jpg',
        dateTime: '2023-09-01T08:00:00',
        description: 'A showcase of the latest gear and experiences for outdoor enthusiasts.',
        maxParticipants: 1500,
        ticketPrice: '0.04 ETH',
        location: 'Mountain View Park, Denver',
        mainGuests: ['Bear Grylls', 'Cheryl Strayed', 'Aron Ralston'],
    },
    {
        id: '7',
        name: 'Film Noir Night',
        displayPicture: 'https://as2.ftcdn.net/v2/jpg/05/96/48/19/1000_F_596481961_4QbFeNdmWCBWC6Wi7D4peGAafVutH7Eg.jpg',
        dateTime: '2023-10-30T20:00:00',
        description: 'A night of classic film noir screenings with live jazz music.',
        maxParticipants: 500,
        ticketPrice: '0.025 ETH',
        location: 'Historic Theater, Los Angeles',
        mainGuests: ['Humphrey Bogart', 'Lauren Bacall', 'Orson Welles'],
    },
];
